// Local-only UI and real accounting. No production account or remote requests.
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { chromium } from 'playwright-core'
const url = 'http://localhost:5196/shipping-ui'
const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--port', '5196', '--strictPort'], { stdio: 'ignore' })
let browser
try {
  for (let i = 0; i < 60; i++) { try { if ((await fetch(url)).ok) break } catch {} await new Promise(r => setTimeout(r, 500)) }
  browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe' })
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.route('**/*', route => {
    const u = new URL(route.request().url())
    if (!['localhost', '127.0.0.1'].includes(u.hostname)) return route.abort()
    if (u.pathname === '/src/main.tsx') return route.fulfill({ contentType: 'application/javascript', body: 'import "/src/index.css";' })
    return route.continue()
  })
  await page.goto(url)
  await page.evaluate(async () => {
    const { db } = await import('/src/db.ts')
    const { default: React } = await import('/node_modules/.vite/deps/react.js')
    const { default: ReactDOM } = await import('/node_modules/.vite/deps/react-dom_client.js')
    const { default: Shipping } = await import('/src/pages/sales/SaleShipping.tsx')
    const c = await db.customers.add({ name: 'مشتری آزمایشی', balance: 0, type: 'wholesale' })
    const id = await db.sales.add({ date: Date.now(), saleType: 'wholesale', customerId: c, customerName: 'مشتری آزمایشی', total: 0, paid: 0, lines: [] })
    await db.cashMovements.add({ date: Date.now(), type: 'capitalIn', amount: 2000 })
    window.testRoot = ReactDOM.createRoot(document.getElementById('root'))
    window.testRoot.render(React.createElement(Shipping, { sale: await db.sales.get(id) }))
    window.customerId = c
    window.result = async () => ({ cash: (await db.cashMovements.toArray()).filter(x => !x.deleted).reduce((a, x) => a + x.amount, 0), debt: (await db.customers.get(c)).balance, active: (await db.payments.toArray()).filter(x => !x.deleted).length })
  })
  await page.getByRole('button', { name: 'ثبت کرایهٔ بار', exact: true }).click()
  await page.getByLabel('کل کرایه (افغانی)', { exact: true }).fill('۵۰۰')
  await page.getByLabel('مسئول کرایه', { exact: true }).selectOption('split')
  await page.getByLabel('سهم مشتری (افغانی)', { exact: true }).fill('۳۰۰')
  await page.getByLabel('دریافت نقدی کرایه از مشتری', { exact: true }).fill('۱۰۰')
  await page.getByText(/قرض کرایه:.*۲۰۰/).waitFor()
  await page.getByLabel('دریافت نقدی کرایه از مشتری', { exact: true }).fill('۴۰۰')
  assert.equal(await page.getByRole('button', { name: 'ذخیرهٔ کرایه', exact: true }).isDisabled(), true)
  await page.getByLabel('دریافت نقدی کرایه از مشتری', { exact: true }).fill('۱۰۰')
  await page.screenshot({ path: 'qa-shipping-form.png', fullPage: true })
  for (const width of [320, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  }
  await page.getByRole('button', { name: 'ذخیرهٔ کرایه', exact: true }).click()
  await page.getByRole('button', { name: 'اصلاح کرایه', exact: true }).waitFor()
  assert.deepEqual(await page.evaluate(() => window.result()), { cash: 1600, debt: 200, active: 1 })
  await page.getByRole('button', { name: 'اصلاح کرایه', exact: true }).click()
  await page.getByLabel('کل کرایه (افغانی)', { exact: true }).fill('۶۰۰')
  await page.getByLabel('مسئول کرایه', { exact: true }).selectOption('customer')
  await page.getByLabel('دلیل اصلاح', { exact: true }).fill('مبلغ اشتباه بود')
  await page.getByRole('button', { name: 'ذخیرهٔ اصلاح', exact: true }).click()
  await page.getByRole('button', { name: 'لغو کرایه', exact: true }).waitFor()
  assert.deepEqual(await page.evaluate(() => window.result()), { cash: 1500, debt: 500, active: 1 })
  await page.getByRole('button', { name: 'لغو کرایه', exact: true }).click()
  await page.getByLabel('دلیل لغو', { exact: true }).fill('ثبت اشتباهی')
  await page.getByRole('button', { name: 'تأیید لغو کرایه', exact: true }).click()
  await page.getByText('هنوز کرایه‌ای ثبت نشده است.').waitFor()
  assert.deepEqual(await page.evaluate(() => window.result()), { cash: 2000, debt: 0, active: 0 })
  // Full Sales page: prepare freight, hold/resume, checkout, and open its details.
  await page.evaluate(async () => {
    const { db } = await import('/src/db.ts')
    const { setOpeningStock } = await import('/src/lib/ops.ts')
    const { writeWorkingSale } = await import('/src/lib/saleDrafts.ts')
    const { default: React } = await import('/node_modules/.vite/deps/react.js')
    const { default: Sales } = await import('/src/pages/Sales.tsx')
    const productId = await db.products.add({ name: 'بوت کرایه', createdAt: Date.now() })
    window.variantId = await db.variants.add({ productId, size: '40', color: 'سیاه', stockQty: 0, purchasePrice: 50, retailPrice: 100, wholesalePrice: 80 })
    await setOpeningStock(window.variantId, 10)
    writeWorkingSale({ saleType: 'wholesale', customerId: window.customerId, lines: [{ variantId: window.variantId, productName: 'بوت کرایه', size: '40', color: 'سیاه', qty: 2, unitPrice: 80 }], paidStr: '', paidTouched: false, discountStr: '', promise: '', bookPage: '' })
    window.testRoot.render(React.createElement(Sales))
  })
  await page.getByRole('button', { name: 'افزودن کرایهٔ بار', exact: true }).click()
  await page.getByLabel('کل کرایه (افغانی)', { exact: true }).fill('50')
  await page.getByRole('button', { name: 'افزودن کرایه به فروش', exact: true }).click()
  assert.deepEqual(await page.evaluate(() => window.result()), { cash: 2000, debt: 0, active: 0 }, 'preparing freight never writes accounts')
  await page.getByRole('button', { name: 'معطل', exact: true }).click()
  await page.getByRole('button', { name: 'ادامه و ثبت', exact: true }).click()
  await page.getByRole('button', { name: 'ویرایش کرایهٔ فروش', exact: true }).waitFor()
  // Two synchronous clicks exercise the pending ref guard, not Playwright waiting.
  await page.getByRole('button', { name: 'ثبت فروش', exact: true }).evaluate(button => { button.click(); button.click() })
  await page.getByText(/فروش ثبت شد/).first().waitFor()
  assert.deepEqual(await page.evaluate(() => window.result()), { cash: 2110, debt: 50, active: 1 })
  assert.equal(await page.evaluate(async () => (await (await import('/src/db.ts')).db.variants.get(window.variantId)).stockQty), 8)
  await page.getByRole('button', { name: 'تاریخچه', exact: true }).click()
  await page.getByRole('button').filter({ hasText: 'بوت کرایه' }).click()
  await page.getByRole('button', { name: 'اصلاح کرایه', exact: true }).waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'qa-shipping-sale-details.png', fullPage: true })
  await page.getByRole('button', { name: 'اصلاح کرایه', exact: true }).click()
  await page.getByLabel('دلیل اصلاح', { exact: true }).fill('آزمایش فقط مشاهده')
  await page.evaluate(async () => { (await import('/src/db.ts')).accessFlags.readOnly = true })
  await page.getByRole('button', { name: 'ذخیرهٔ اصلاح', exact: true }).click()
  assert.deepEqual(await page.evaluate(() => window.result()), { cash: 2110, debt: 50, active: 1 }, 'read-only change while dialog open prevents writes')
  assert.deepEqual(errors, [])
  console.log('PASS: freight create/correct/cancel UI, Dari inputs, responsive layout, held draft, atomic double-click checkout, Sales history and read-only guard')
} finally { await browser?.close(); server.kill() }
