// Generates src/themes.css — the «شب» (dark) and «آفتاب» (sunlight, high contrast) display modes.
// Tailwind 4 reads every colour from a CSS variable, so a mode only has to redefine those
// variables under :root[data-theme]; no component class changes. Run: node scripts/gen-themes.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const theme = readFileSync(new URL('../node_modules/tailwindcss/theme.css', import.meta.url), 'utf8')
const HUES = ['amber', 'blue', 'emerald', 'green', 'indigo', 'orange', 'purple', 'red']
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]
const tw = (hue, shade) => {
  const m = theme.match(new RegExp(`--color-${hue}-${shade}:\\s*([^;]+);`))
  if (!m) throw new Error(`missing ${hue}-${shade}`)
  return m[1].trim()
}
// The app's own neutral and money palettes (index.css @theme) — light values, used for pinned backgrounds.
const LIGHT = {
  slate: { 700: '#3A3A42', 800: '#27272D', 900: '#1D1D1F', 950: '#111113' },
  teal: { 600: '#326657', 700: '#244d42', 800: '#1c3d34', 900: '#18332c' }
}
const DARK_SURFACE = '#1C1C1E'
const mix = (color, pct) => `color-mix(in oklab, ${color} ${pct}%, ${DARK_SURFACE})`

const out = []
out.push('/* GENERATED by scripts/gen-themes.mjs — edit the script, not this file. */')

// ---------- شب (dark) ----------
const dark = [
  'color-scheme: dark;',
  '--canvas: #111113;', `--surface: ${DARK_SURFACE};`, '--surface-grouped: #2C2C2E;',
  '--text-primary: #F2F2F7;', '--text-secondary: #B4B4BC;',
  '--border-subtle: #2F2F33;', '--border-control: #56565C;',
  '--action: #5A9CF5;', '--action-fill: #2563C9;', '--action-pressed: #1E50A6;', '--action-tint: #15243A;',
  '--success: #6FBFA5;', '--warning: #E0A43A;', '--danger: #FF7A7A;',
  '--danger-tint: #3A1D1F;', '--warning-tint: #3A2E14;', '--warning-text: #F2C46B;',
  '--toast-bg: #3A3A3C;', '--shadow-color: 0 0 0;',
  '--color-slate-50: #242427;', '--color-slate-100: #2C2C2E;', '--color-slate-200: #3A3A3C;', '--color-slate-300: #56565C;',
  '--color-slate-400: #8E8E93;', '--color-slate-500: #B4B4BC;', '--color-slate-600: #BDBDC3;', '--color-slate-700: #D1D1D6;',
  '--color-slate-800: #E5E5EA;', '--color-slate-900: #F2F2F7;', '--color-slate-950: #FFFFFF;',
  `--color-teal-50: ${mix('#326657', 30)};`, `--color-teal-100: ${mix('#326657', 45)};`, `--color-teal-200: ${mix('#326657', 60)};`,
  '--color-teal-300: #5FA58E;', '--color-teal-400: #6FBFA5;', '--color-teal-600: #6FBFA5;', '--color-teal-700: #7FCDB3;',
  '--color-teal-800: #9AD8C3;', '--color-teal-900: #B5E3D3;'
]
for (const hue of HUES) {
  const map = { 50: mix(tw(hue, 500), 14), 100: mix(tw(hue, 500), 22), 200: mix(tw(hue, 500), 32), 300: mix(tw(hue, 500), 48),
    400: tw(hue, 400), 500: tw(hue, 400), 600: tw(hue, 300), 700: tw(hue, 300), 800: tw(hue, 200), 900: tw(hue, 100), 950: tw(hue, 50) }
  for (const s of SHADES) dark.push(`--color-${hue}-${s}: ${map[s]};`)
}
const darkRoot = ':root[data-theme="dark"]'
out.push(`${darkRoot} {\n  ${dark.join('\n  ')}\n}`)
// Strong backgrounds carry white text: keep their light-mode colour so the text stays readable.
const pinned = []
for (const hue of HUES) for (const s of [500, 600, 700, 800, 900, 950]) pinned.push(`${darkRoot} .bg-${hue}-${s} { background-color: ${tw(hue, s)}; }`)
for (const [pal, shades] of Object.entries(LIGHT)) for (const [s, v] of Object.entries(shades)) pinned.push(`${darkRoot} .bg-${pal}-${s} { background-color: ${pal === 'slate' ? '#3A3A3C' : v}; }`)
out.push(...pinned)
out.push(`${darkRoot} .bg-white { background-color: var(--surface); }`)
out.push(`${darkRoot} img { filter: brightness(0.92); }`)

// ---------- آفتاب (sunlight: light, stronger contrast) ----------
const sun = [
  '--canvas: #EDEDF0;', '--surface: #FFFFFF;', '--surface-grouped: #E3E3E8;',
  '--text-primary: #000000;', '--text-secondary: #33333A;',
  '--border-subtle: #BDBDC3;', '--border-control: #6F6F77;',
  '--action: #0050A8;', '--action-fill: #0050A8;', '--action-pressed: #003F85;', '--action-tint: #DCE9FF;',
  '--success: #1C4D40;', '--warning: #7C4A03;', '--danger: #991B1B;',
  '--color-slate-200: #BDBDC3;', '--color-slate-300: #8E8E93;', '--color-slate-400: #45454D;', '--color-slate-500: #33333A;',
  '--color-slate-600: #27272D;', '--color-slate-700: #1D1D1F;', '--color-slate-800: #111113;', '--color-slate-900: #000000;',
  '--color-teal-600: #1C3D34;', '--color-teal-700: #18332C;', '--color-teal-800: #10231E;'
]
for (const hue of HUES) {
  const map = { 400: tw(hue, 600), 500: tw(hue, 700), 600: tw(hue, 800), 700: tw(hue, 800), 800: tw(hue, 900), 900: tw(hue, 950) }
  for (const [s, v] of Object.entries(map)) sun.push(`--color-${hue}-${s}: ${v};`)
}
out.push(`:root[data-theme="sun"] {\n  ${sun.join('\n  ')}\n}`)

writeFileSync(new URL('../src/themes.css', import.meta.url), out.join('\n') + '\n')
console.log('wrote src/themes.css')
